### ISSUE TITLE
🔡 Fix wording `s/usage/permissions/`

### ISSUE THREAD

**Issue by stoe** [ActionsDesk/report-action-permissions#2]
https://github.com/ActionsDesk/report-action-permissions/blob/d1d9b2af3b5ef7244382665d440c4df607a5a46e/action.js#L65
https://github.com/ActionsDesk/report-action-permissions/blob/d1d9b2af3b5ef7244382665d440c4df607a5a46e/action.js#L88

Those should read `Save/Update GitHub Actions permissions report`.

**Comment by mohitsaxenaknoldus** [comment]
Can I raise a PR for this?

**Comment by stoe** [comment]
@mohitsaxenaknoldus please do

**Comment by mohitsaxenaknoldus** [comment]
PR: https://github.com/ActionsDesk/report-action-permissions/pull/8
